from pydantic import *
from typing import Optional, List
from ..base import *

class Task_Restriction(BackboneElement):
	repetitions: Optional[PositiveInt] = None
	period: Optional[Period] = None
	recipient: Optional[List[Reference]] = None

class Task_Output(BackboneElement):
	valueBase64Binary: Optional[str] = None
	valueAge: Optional[Age] = None
	valueParameterDefinition: Optional[ParameterDefinition] = None
	valueTiming: Optional[Timing] = None
	valueCode: Optional[str] = None
	valueReference: Optional[Reference] = None
	valueContributor: Optional[Contributor] = None
	valueContactDetail: Optional[ContactDetail] = None
	valueUri: Optional[str] = None
	valueUsageContext: Optional[UsageContext] = None
	valueTime: Optional[str] = None
	valueDecimal: Optional[float] = None
	valueCanonical: Optional[str] = None
	valueMarkdown: Optional[str] = None
	valueIdentifier: Optional[Identifier] = None
	valueTriggerDefinition: Optional[TriggerDefinition] = None
	valueQuantity: Optional[Quantity] = None
	valueCount: Optional[Count] = None
	valueString: Optional[str] = None
	valueRatio: Optional[Ratio] = None
	valueBoolean: Optional[bool] = None
	valueInstant: Optional[str] = None
	valueDateTime: Optional[str] = None
	valueDate: Optional[str] = None
	type: CodeableConcept
	valueDuration: Optional[Duration] = None
	valueDataRequirement: Optional[DataRequirement] = None
	valueMeta: Optional[Meta] = None
	valueMoney: Optional[Money] = None
	valueCoding: Optional[Coding] = None
	valueExpression: Optional[Expression] = None
	valueSampledData: Optional[SampledData] = None
	valueDosage: Optional[Dosage] = None
	valueContactPoint: Optional[ContactPoint] = None
	valueCodeableConcept: Optional[CodeableConcept] = None
	valueAnnotation: Optional[Annotation] = None
	valuePeriod: Optional[Period] = None
	valueDistance: Optional[Distance] = None
	valueRange: Optional[Range] = None
	valueSignature: Optional[Signature] = None
	valueUuid: Optional[str] = None
	valueInteger: Optional[int] = None
	valueHumanName: Optional[HumanName] = None
	valueUnsignedInt: Optional[NonNegativeInt] = None
	valueAttachment: Optional[Attachment] = None
	valueOid: Optional[str] = None
	valueAddress: Optional[Address] = None
	valueRelatedArtifact: Optional[RelatedArtifact] = None
	valuePositiveInt: Optional[PositiveInt] = None
	valueId: Optional[str] = None
	valueUrl: Optional[str] = None

class Task_Input(BackboneElement):
	valueBase64Binary: Optional[str] = None
	valueAge: Optional[Age] = None
	valueParameterDefinition: Optional[ParameterDefinition] = None
	valueTiming: Optional[Timing] = None
	valueCode: Optional[str] = None
	valueReference: Optional[Reference] = None
	valueContributor: Optional[Contributor] = None
	valueContactDetail: Optional[ContactDetail] = None
	valueUri: Optional[str] = None
	valueUsageContext: Optional[UsageContext] = None
	valueTime: Optional[str] = None
	valueDecimal: Optional[float] = None
	valueCanonical: Optional[str] = None
	valueMarkdown: Optional[str] = None
	valueIdentifier: Optional[Identifier] = None
	valueTriggerDefinition: Optional[TriggerDefinition] = None
	valueQuantity: Optional[Quantity] = None
	valueCount: Optional[Count] = None
	valueString: Optional[str] = None
	valueRatio: Optional[Ratio] = None
	valueBoolean: Optional[bool] = None
	valueInstant: Optional[str] = None
	valueDateTime: Optional[str] = None
	valueDate: Optional[str] = None
	type: CodeableConcept
	valueDuration: Optional[Duration] = None
	valueDataRequirement: Optional[DataRequirement] = None
	valueMeta: Optional[Meta] = None
	valueMoney: Optional[Money] = None
	valueCoding: Optional[Coding] = None
	valueExpression: Optional[Expression] = None
	valueSampledData: Optional[SampledData] = None
	valueDosage: Optional[Dosage] = None
	valueContactPoint: Optional[ContactPoint] = None
	valueCodeableConcept: Optional[CodeableConcept] = None
	valueAnnotation: Optional[Annotation] = None
	valuePeriod: Optional[Period] = None
	valueDistance: Optional[Distance] = None
	valueRange: Optional[Range] = None
	valueSignature: Optional[Signature] = None
	valueUuid: Optional[str] = None
	valueInteger: Optional[int] = None
	valueHumanName: Optional[HumanName] = None
	valueUnsignedInt: Optional[NonNegativeInt] = None
	valueAttachment: Optional[Attachment] = None
	valueOid: Optional[str] = None
	valueAddress: Optional[Address] = None
	valueRelatedArtifact: Optional[RelatedArtifact] = None
	valuePositiveInt: Optional[PositiveInt] = None
	valueId: Optional[str] = None
	valueUrl: Optional[str] = None

class Task(DomainResource):
	restriction: Optional[Task_Restriction] = None
	description: Optional[str] = None
	performerType: Optional[List[CodeableConcept]] = None
	executionPeriod: Optional[Period] = None
	insurance: Optional[List[Reference]] = None
	instantiatesCanonical: Optional[str] = None
	instantiatesUri: Optional[str] = None
	relevantHistory: Optional[List[Reference]] = None
	encounter: Optional[Reference] = None
	reasonCode: Optional[CodeableConcept] = None
	statusReason: Optional[CodeableConcept] = None
	authoredOn: Optional[str] = None
	output: Optional[List[Task_Output]] = None
	businessStatus: Optional[CodeableConcept] = None
	note: Optional[List[Annotation]] = None
	for_: Optional[Reference] = None
	requester: Optional[Reference] = None
	lastModified: Optional[str] = None
	priority: Optional[str] = None
	status: str
	groupIdentifier: Optional[Identifier] = None
	code: Optional[CodeableConcept] = None
	identifier: Optional[List[Identifier]] = None
	intent: str
	focus: Optional[Reference] = None
	input: Optional[List[Task_Input]] = None
	basedOn: Optional[List[Reference]] = None
	partOf: Optional[List[Reference]] = None
	location: Optional[Reference] = None
	owner: Optional[Reference] = None
	reasonReference: Optional[Reference] = None