from typing import Optional
from ..base import *

class Task_Restriction(BackboneElement):
	period: Optional[Period] = None
	recipient: list[Reference] = []
	repetitions: Optional[str] = None

class Task_Output(BackboneElement):
	valueBase64Binary: Optional[str] = None
	valueAge: Optional[str] = None
	valueParameterDefinition: Optional[ParameterDefinition] = None
	valueTiming: Optional[str] = None
	valueCode: Optional[str] = None
	valueReference: Optional[Reference] = None
	valueContributor: Optional[Contributor] = None
	valueContactDetail: Optional[ContactDetail] = None
	valueUri: Optional[str] = None
	valueUsageContext: Optional[UsageContext] = None
	valueTime: Optional[str] = None
	valueDecimal: Optional[str] = None
	valueCanonical: Optional[str] = None
	valueMarkdown: Optional[str] = None
	valueIdentifier: Optional[Identifier] = None
	valueTriggerDefinition: Optional[TriggerDefinition] = None
	valueQuantity: Optional[Quantity] = None
	valueCount: Optional[str] = None
	valueString: Optional[str] = None
	valueRatio: Optional[Ratio] = None
	valueBoolean: Optional[bool] = None
	valueInstant: Optional[str] = None
	valueDateTime: Optional[str] = None
	valueDate: Optional[str] = None
	type: CodeableConcept
	valueDuration: Optional[str] = None
	valueDataRequirement: Optional[DataRequirement] = None
	valueMeta: Optional[Meta] = None
	valueMoney: Optional[Money] = None
	valueCoding: Optional[Coding] = None
	valueExpression: Optional[Expression] = None
	valueSampledData: Optional[SampledData] = None
	valueDosage: Optional[str] = None
	valueContactPoint: Optional[ContactPoint] = None
	valueCodeableConcept: Optional[CodeableConcept] = None
	valueAnnotation: Optional[Annotation] = None
	valuePeriod: Optional[Period] = None
	valueDistance: Optional[str] = None
	valueRange: Optional[Range] = None
	valueSignature: Optional[Signature] = None
	valueUuid: Optional[str] = None
	valueInteger: Optional[int] = None
	valueHumanName: Optional[HumanName] = None
	valueUnsignedInt: Optional[str] = None
	valueAttachment: Optional[Attachment] = None
	valueOid: Optional[str] = None
	valueAddress: Optional[Address] = None
	valueRelatedArtifact: Optional[RelatedArtifact] = None
	valuePositiveInt: Optional[str] = None
	valueId: Optional[str] = None
	valueUrl: Optional[str] = None

class Task_Input(BackboneElement):
	valueBase64Binary: Optional[str] = None
	valueAge: Optional[str] = None
	valueParameterDefinition: Optional[ParameterDefinition] = None
	valueTiming: Optional[str] = None
	valueCode: Optional[str] = None
	valueReference: Optional[Reference] = None
	valueContributor: Optional[Contributor] = None
	valueContactDetail: Optional[ContactDetail] = None
	valueUri: Optional[str] = None
	valueUsageContext: Optional[UsageContext] = None
	valueTime: Optional[str] = None
	valueDecimal: Optional[str] = None
	valueCanonical: Optional[str] = None
	valueMarkdown: Optional[str] = None
	valueIdentifier: Optional[Identifier] = None
	valueTriggerDefinition: Optional[TriggerDefinition] = None
	valueQuantity: Optional[Quantity] = None
	valueCount: Optional[str] = None
	valueString: Optional[str] = None
	valueRatio: Optional[Ratio] = None
	valueBoolean: Optional[bool] = None
	valueInstant: Optional[str] = None
	valueDateTime: Optional[str] = None
	valueDate: Optional[str] = None
	type: CodeableConcept
	valueDuration: Optional[str] = None
	valueDataRequirement: Optional[DataRequirement] = None
	valueMeta: Optional[Meta] = None
	valueMoney: Optional[Money] = None
	valueCoding: Optional[Coding] = None
	valueExpression: Optional[Expression] = None
	valueSampledData: Optional[SampledData] = None
	valueDosage: Optional[str] = None
	valueContactPoint: Optional[ContactPoint] = None
	valueCodeableConcept: Optional[CodeableConcept] = None
	valueAnnotation: Optional[Annotation] = None
	valuePeriod: Optional[Period] = None
	valueDistance: Optional[str] = None
	valueRange: Optional[Range] = None
	valueSignature: Optional[Signature] = None
	valueUuid: Optional[str] = None
	valueInteger: Optional[int] = None
	valueHumanName: Optional[HumanName] = None
	valueUnsignedInt: Optional[str] = None
	valueAttachment: Optional[Attachment] = None
	valueOid: Optional[str] = None
	valueAddress: Optional[Address] = None
	valueRelatedArtifact: Optional[RelatedArtifact] = None
	valuePositiveInt: Optional[str] = None
	valueId: Optional[str] = None
	valueUrl: Optional[str] = None

class Task(DomainResource):
	restriction: Optional[Task_Restriction] = None
	description: Optional[str] = None
	performerType: list[CodeableConcept] = []
	executionPeriod: Optional[Period] = None
	insurance: list[Reference] = []
	instantiatesCanonical: Optional[str] = None
	instantiatesUri: Optional[str] = None
	relevantHistory: list[Reference] = []
	encounter: Optional[Reference] = None
	reasonCode: Optional[CodeableConcept] = None
	statusReason: Optional[CodeableConcept] = None
	authoredOn: Optional[str] = None
	output: list[Task_Output] = []
	businessStatus: Optional[CodeableConcept] = None
	note: list[Annotation] = []
	for_: Optional[Reference] = None
	requester: Optional[Reference] = None
	lastModified: Optional[str] = None
	priority: Optional[str] = None
	status: str
	groupIdentifier: Optional[Identifier] = None
	code: Optional[CodeableConcept] = None
	identifier: list[Identifier] = []
	intent: str
	focus: Optional[Reference] = None
	input: list[Task_Input] = []
	basedOn: list[Reference] = []
	partOf: list[Reference] = []
	location: Optional[Reference] = None
	owner: Optional[Reference] = None
	reasonReference: Optional[Reference] = None

